---
name: deploy pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: docs
